#!/usr/bin/env python
import argparse
import os
import os.path
from dotman import stow, get_linkable_files



def cli():
    parser =argparse.ArgumentParser()
    parser.add_argument("-s", "--simulate", action="store_true", default=False, help="Simulate, with no actions on the filesystem.")
    parser.add_argument("-v", "--verbose", action="store_true", default=True)
    parser.add_argument("-a", "--app", help="Application name to stow its configs.")
    parser.add_argument("-d", "--dest", default=os.path.expanduser("~"))
    parser.add_argument("-f", "--force", action="store_true", default=False, help="force linking")
    res = parser.parse_args()
    apppath = os.path.realpath(res.app)

    stow(get_linkable_files(apppath, dest=res.dest), simulate=res.simulate, verbose=res.verbose, force=res.force)
    

if __name__ == "__main__":
    cli()
